name: linux_build
on: [workflow_dispatch]
jobs:
    Build:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout
          uses: actions/checkout@v3.3.0
          with:
            repository: aseprite/aseprite
            ref: v1.3-beta21
            submodules: true
        - name: Install packages
          run: |
            sudo apt update -y
            sudo apt upgrade -y
            sudo apt install -y g++ clang-10 libc++-10-dev libc++abi-10-dev cmake ninja-build libx11-dev libxcursor-dev libxi-dev libgl1-mesa-dev libfontconfig1-dev
