name: linux_build
on: [workflow_dispatch]
jobs:
    Build:
      runs-on: ubuntu-18.04
      steps:
        - name: Install dependencies
          run: |
            sudo apt-get install -y g++ clang-10 libc++-10-dev libc++abi-10-dev cmake ninja-build libx11-dev libxcursor-dev libxi-dev libgl1-mesa-dev libfontconfig1-dev
        - name: Clone aseprite
          run: |
            git clone -b v1.3-beta21 --single-branch --recursive https://github.com/aseprite/aseprite.git
        - name: Clone depot_tools
          run: |
            git clone https://chromium.googlesource.com/chromium/tools/depot_tools.git
        - name: Clone skia
          run: |
            git clone -b aseprite-m102 --single-branch https://github.com/aseprite/skia.git
        - name: Build skia
          run: |
            export PATH="${PWD}/depot_tools:${PATH}"
            cd ./skia
            python tools/git-sync-deps
            gn gen out/Release-x64 --args="is_debug=false is_official_build=true skia_use_system_expat=false skia_use_system_icu=false skia_use_system_libjpeg_turbo=false skia_use_system_libpng=false skia_use_system_libwebp=false skia_use_system_zlib=false skia_use_sfntly=false skia_use_freetype=true skia_use_harfbuzz=true skia_pdf_subset_harfbuzz=true skia_use_system_freetype2=false skia_use_system_harfbuzz=false"
            ninja -C out/Release-x64 skia modules
            cd ..
        - name: Build aseprite
          run: |
            cd aseprite
            mkdir build
            cd build
            export CC=clang
            export CXX=clang++
            cmake \
              -DCMAKE_BUILD_TYPE=RelWithDebInfo \
              -DCMAKE_CXX_FLAGS:STRING=-stdlib=libc++ \
              -DCMAKE_EXE_LINKER_FLAGS:STRING=-stdlib=libc++ \
              -DLAF_BACKEND=skia \
              -DSKIA_DIR=../../skia \
              -DSKIA_LIBRARY_DIR=../../skia/out/Release-x64 \
              -DSKIA_LIBRARY=../../skia/out/Release-x64/libskia.a \
              -G Ninja \
              ..
            ninja aseprite
