name: linux_build
on: [workflow_dispatch]
jobs:
    Build:
      runs-on: ubuntu-18.04
      steps:
        - name: Create folders
          run: |
            git clone -b v1.3-beta21 --single-branch --recursive https://github.com/aseprite/aseprite.git
            git clone https://chromium.googlesource.com/chromium/tools/depot_tools.git
            git clone -b aseprite-m102 --single-branch https://github.com/aseprite/skia.git
            export PATH="${PWD}/depot_tools:${PATH}"
            cd ./skia
            python tools/git-sync-deps
            gn gen out/Release-x64 --args="is_debug=false is_official_build=true skia_use_system_expat=false skia_use_system_icu=false skia_use_system_libjpeg_turbo=false skia_use_system_libpng=false skia_use_system_libwebp=false skia_use_system_zlib=false skia_use_sfntly=false skia_use_freetype=true skia_use_harfbuzz=true skia_pdf_subset_harfbuzz=true skia_use_system_freetype2=false skia_use_system_harfbuzz=false"
            ninja -C out/Release-x64 skia modules
